name: Generate Daily Sitemap

on:
  schedule:
    - cron: '0 0 * * *' # تشغيل كل يوم الساعة 12 بالليل
  workflow_dispatch: # إمكانية التشغيل يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Sitemap
        run: python generate_sitemaps.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/sitemap.xml
          git commit -m "Auto-update sitemap [skip ci]" || echo "No changes to commit"
          git push
