name: Auto Generate Sitemaps

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Sitemap Generator Script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          SITE_BASE_URL: "https://yamenhadidi37-cell.github.io/flxjo-store"
        run: python generate_sitemaps.py

      - name: Commit and push generated sitemaps to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 Auto-update movie sitemaps [skip ci]"
          branch: main
          file_pattern: 'public/sitemap.xml'
